---
partner_id: "71908401054"
partner_key: 692a126ba6b5119736656c382ab3041f
bonus_multiplier: 1
api_url: https://trumthe.vn/chargingws/v2
api_timeout: 10
check_interval: 30
debug:
  enabled: true
  notify_admins: true
  categories:
    general: true
    payment: true
    api: true
...
