---
name: Donate
version: 0.0.1
main: Donate\Donate
src-namespace-prefix: Donate
api: 5.0.0
authors: [hachkingtohach1, TungstenVN, NhanAZ]

commands:
  donate:
    description: "Nạp thẻ"
    permission: donate.command
    aliases: [napthe]

# TODO: Top Donate

permissions:
  donate.command:
    default: true
...
