---
name: NapThe
version: 0.0.1
main: hachkingtohach1\NapThe\Main
api: 5.0.0
author: hachkingtohach1
authors: [TungstenVN, NhanAZ]

commands:
  napthe:
    description: "Nạp thẻ"
    permission: napthe.command

# TODO: Top Donate

permissions:
  napthe.command:
    default: true
...
