---
name: Donate
version: 1.0.0
main: Donate\Donate
src-namespace-prefix: Donate
api: 5.0.0
extensions: [json]
authors: [NhanAZ, hachkingtohach1, TungstenVN]
description: Plugin nạp thẻ cho máy chủ PMMP
website: https://github.com/NhanAZ/Donate
php: [8.3.0]
softdepend: [pmforms]

commands:
  donate:
    description: "Mở giao diện nạp thẻ"
    permission: donate.command.donate
    usage: "/donate"
  topdonate:
    description: "Xem bảng xếp hạng người nạp thẻ"
    permission: donate.command.topdonate
    usage: "/topdonate [trang]"
  donatedebug:
    description: "Kiểm tra thông tin debug của plugin nạp thẻ"
    permission: donate.command.debug
    usage: "/donatedebug [pending|status <requestId>]"

permissions:
  donate.command.donate:
    default: true
    description: "Cho phép sử dụng lệnh /donate"
  donate.command.topdonate:
    default: true
    description: "Cho phép sử dụng lệnh /topdonate"
  donate.command.debug:
    default: op
    description: "Cho phép sử dụng lệnh /donatedebug"
  donate.admin:
    default: op
    description: "Cấp quyền admin cho plugin nạp thẻ"
...
