---
# Donate Plugin Configuration

# Partner credentials (từ trumthe.vn)
partner_id: ""  # ID đối tác
partner_key: "" # Khóa API đối tác

# Reward settings
bonus_multiplier: 1.0  # Hệ số nhân điểm khi nạp thẻ thành công (1.0 = 100%)

# API settings
api_url: "https://trumthe.vn/chargingws/v2"
api_timeout: 10  # Thời gian timeout khi gọi API (giây)

# Task settings
check_interval: 30  # Kiểm tra trạng thái thanh toán sau mỗi x giây 