name: PHP CS Fixer

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --ignore-platform-req=ext-chunkutils2 --ignore-platform-req=ext-pmmpthread --ignore-platform-req=ext-crypto

    - name: Run CS Fixer
      run: composer cs-fix

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply PHP CS Fixer changes" 